export const GET_MOVIES_HUNTER = 'GET_MOVIES_HUNTER';
export const SEARCH_FILTER = 'SEARCH_FILTER';
export const SORT_FILTER = 'SORT_FILTER';
export const SORT_MOVIES = 'SORT_MOVIES';

export const GET_MOVIES_DETAILS = 'GET_MOVIES_DETAILS';
export const CHOOSE_MOVIE_DETAILS = 'CHOOSE_MOVIE_DETAILS';
export const PASS_CHOSEN_MOVIE = 'PASS_CHOSEN_MOVIE';
